### ISSUE TITLE
How stable are these drivers?  (re: MQTT)

### ISSUE THREAD

**Issue by sofakng** [davidmassot/Berto#12]
Are these drivers (MQTT) considered stable?  I'm just wondering before I deploy any of them.

Also, GitHub only shows 1 commit 4 hours ago but I thought these have been available for a little while?

Thanks!

**Comment by davidmassot** [comment]
I've been using now for several years so consider stable, noble;y recently opened up to public and used GitHub purely for download.

**Comment by dacorn** [comment]
Hi David, thank you so much for building and publishing this, I have been looking for MQTT support for a long time. This opens many doors for control4.  Do you have any instructions for the driver for MQTT?  I am new to control4 programming. Thanks!
Dave
