### ISSUE TITLE
MQTT driver: clientId setting missing

### ISSUE THREAD

**Issue by neophob** [davidmassot/Berto#3]
Hi, thanks for the MQTT driver!

I wanted to connect it to a test instance of internetofthings.ibmcloud.com - however there you need a defined clientId, else the connection will not succeed.

Do you think you could add this to the settings (and the of course use this setting to connect)?

**Comment by davidmassot** [comment]
Version 5 available with Client Id added.

**Comment by neophob** [comment]
Wow @davidmassot thanks, that was fast! However its weird, when I want to connect I see those messages in the debug log:

```
DEBUG: Initialising MQTT Broker Connection
DEBUG: Subscription Process Started
DEBUG: Subscriptions Not Refreshed As Not Connected
```
Also `Last Message` and `Last Update` is not updated, even when data is transfered (I subscribed to the # topic)

Can I enable more debugging?

**Comment by davidmassot** [comment]
Michael

I am not familiar with the IBM Not service but the debug message you are getting suggests that the MQTT Bridge is has connected to the broker, send a CONNECT packet but has not received a CONNACK.

Thanks

**Comment by davidmassot** [comment]
Michael,

Have done some testing using my own account and the Quickstart option and have got them both to connect.

I have to set the Client Id to d:Orgid or Quickstart:DeviceType:DeviceId, see enclosed.

Using my Ord Id I then set the username to use-auth-token and the password to the generated token.

All connected and subscribed fine.

Thanks

**Comment by neophob** [comment]
Thanks - it looks like I did a mistake when query the data!

minor: there's a type on the docs:
> MQTT client Id otehrwise
