### ISSUE TITLE
MQTT driver: define QoS

### ISSUE THREAD

**Issue by neophob** [davidmassot/Berto#4]
Today the MQTT driver use per default QoS 2 - depending on the use case QoS 0 or 1 might be enough. 

Would be fantastic when the user could define the QoS level in the settings!

**Comment by davidmassot** [comment]
QoS added.

I was able to get connected by could not subscribe to any topics, how did you achieve that? Can you show me your setup?

Thanks

**Comment by neophob** [comment]
Damn you fast @davidmassot, thanks!

I also wasn't able to subscribe to any of my Watson IoT messages (free account), but I switched over to (local) mosquitto - where it just works. I assume I didn't get the theory right how to query data correctly in Watson IoT - probably because I needed the same client Id for two connections

**Comment by davidmassot** [comment]
I got subscriptions working.

Basically when you create a Device on IoT it can publish messages but can only subscribe to commands, I got his working with mosqiotto_sub first.

You can subscribe to iot-2/cmd/test-command/fmt/json, replace test-command with any command you like.

**Comment by neophob** [comment]
Thanks! Works as desired!
