### ISSUE TITLE
If you select devices that are not lights the Home Assistant driver crashes

### ISSUE THREAD

**Issue by harperreed** [davidmassot/Berto#7]
Here is the error: 
squish.lua:2902: bad argument #1 to 'pairs' (table expected, got nil) (ReceivedFromNetwork)

If you select any devices (rooms) that are not lights the driver crashes with that error. You can remedy it by unselecting covers, locks, etc.

**Comment by davidmassot** [comment]
All other devices should now be added.

Thanks
